Position.create(name: 'System Administrator')
Team.create(name: 'System', acronym: 'SYS', type_id: 3)
Status.create(name: 'unknown')
Status.create(name: 'lost')
Status.create(name: 'out of order')
Status.create(name: 'registered')
Status.create(name: 'removed')
Currency.create(name: 'EUR')
Currency.create(name: 'USD')
admin = User.create(email: 'lechuga@icloud.com', password: 'stemcell', password_confirmation: 'stemcell', firstname: 'Marc', lastname: 'Lechuga', username: 'mlechuga', location_id: 1, role: 'superadmin')
Type.create(name: 'Research team')
Type.create(name: 'Facility')
Type.create(name: 'System')
Team.create(name: 'All')
Department.create(name: 'system', organization_id: 1)
#Option.create(display_all: false)
