Team.create(name: 'System', acronym: 'SYS', type_id: 3)
Status.create(name: 'unknown')
Status.create(name: 'lost')
Status.create(name: 'out of order')
Status.create(name: 'registered')
Status.create(name: 'removed')
Currency.create(name: 'EUR')
Currency.create(name: 'USD')
Type.create(name: 'Research team')
Type.create(name: 'Facility')
Type.create(name: 'System')
Team.create(name: 'All')
Department.create(name: 'system', organization_id: 1)
